# 1.0 Data Wrangling

## 1.1 Imports

In [52]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

## 1.2 Load the data

In [53]:
df_upper = pd.read_csv("datasets/walmart.csv")

In [54]:
df = df_upper.copy()
df.columns = [i.lower() for i in df.columns]

## 1.3 Explore the Data

In [55]:
df.head()

,store,date,weekly_sales,holiday_flag,temperature,fuel_price,cpi,unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106

In [56]:
df.tail()

,store,date,weekly_sales,holiday_flag,temperature,fuel_price,cpi,unemployment
6430,45,28-09-2012,713173.95,0,64.88,3.997,192.013558,8.684
6431,45,05-10-2012,733455.07,0,64.89,3.985,192.170412,8.667
6432,45,12-10-2012,734464.36,0,54.47,4.000,192.327265,8.667
6433,45,19-10-2012,718125.53,0,56.47,3.969,192.330854,8.667
6434,45,26-10-2012,760281.43,0,58.85,3.882,192.308899,8.667

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6435 entries, 0 to 6434
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   store         6435 non-null   int64
 1   date          6435 non-null   object
 2   weekly_sales  6435 non-null   float64
 3   holiday_flag  6435 non-null   int64
 4   temperature   6435 non-null   float64
 5   fuel_price    6435 non-null   float64
 6   cpi           6435 non-null   float64
 7   unemployment  6435 non-null   float64
dtypes: float64(5), int64(2), object(1)
memory usage: 402.3+ KB

In [58]:
df.describe()

,store,weekly_sales,holiday_flag,temperature,fuel_price,cpi,unemployment
count,6435.000000,6.435000e+03,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000
mean,23.000000,1.046965e+06,0.069930,60.663782,3.358607,171.578394,7.999151
std,12.988182,5.643666e+05,0.255049,18.444933,0.459020,39.356712,1.875885
min,1.000000,2.099862e+05,0.000000,-2.060000,2.472000,126.064000,3.879000
25%,12.000000,5.533501e+05,0.000000,47.460000,2.933000,131.735000,6.891000
50%,23.000000,9.607460e+05,0.000000,62.670000,3.445000,182.616521,7.874000
75%,34.000000,1.420159e+06,0.000000,74.940000,3.735000,212.743293,8.622000
max,45.000000,3.818686e+06,1.000000,100.140000,4.468000,227.232807,14.313000

In [59]:
df.isna().sum()

store           0
date            0
weekly_sales    0
holiday_flag    0
temperature     0
fuel_price      0
cpi             0
unemployment    0
dtype: int64

In [60]:
df.isnull().sum()

store           0
date            0
weekly_sales    0
holiday_flag    0
temperature     0
fuel_price      0
cpi             0
unemployment    0
dtype: int64

In [61]:
df.dtypes

store             int64
date             object
weekly_sales    float64
holiday_flag      int64
temperature     float64
fuel_price      float64
cpi             float64
unemployment    float64
dtype: object

In [62]:
df_gb_store = df.groupby("store")

In [63]:
for i,j in df_gb_store:
    print("Store: ",i,"\n\n",j,"\n\n NEXT \n\n")

Store:  1

      store        date  weekly_sales  holiday_flag  temperature  fuel_price  \
0        1  05-02-2010    1643690.90             0        42.31       2.572
1        1  12-02-2010    1641957.44             1        38.51       2.548
2        1  19-02-2010    1611968.17             0        39.93       2.514
3        1  26-02-2010    1409727.59             0        46.63       2.561
4        1  05-03-2010    1554806.68             0        46.50       2.625
..     ...         ...           ...           ...          ...         ...
138      1  28-09-2012    1437059.26             0        76.08       3.666
139      1  05-10-2012    1670785.97             0        68.55       3.617
140      1  12-10-2012    1573072.81             0        62.99       3.601
141      1  19-10-2012    1508068.77             0        67.97       3.594
142      1  26-10-2012    1493659.74             0        69.16       3.506

            cpi  unemployment
0    211.096358         8.106
1    211.242170         8.106
2    211.289143         8.106
3    211.319643         8.106
4    211.350143         8.106
..          ...           ...
138  222.981658         6.908
139  223.181477         6.573
140  223.381296         6.573
141  223.425723         6.573
142  223.444251         6.573

[143 rows x 8 columns]

 NEXT


Store:  2

      store        date  weekly_sales  holiday_flag  temperature  fuel_price  \
143      2  05-02-2010    2136989.46             0        40.19       2.572
144      2  12-02-2010    2137809.50             1        38.49       2.548
145      2  19-02-2010    2124451.54             0        39.69       2.514
146      2  26-02-2010    1865097.27             0        46.10       2.561
147      2  05-03-2010    1991013.13             0        47.17       2.625
..     ...         ...           ...           ...          ...         ...
281      2  28-09-2012    1746470.56             0        79.45       3.666
282      2  05-10-2012    1998321.04             0        70.27       3.617
283      2  12-10-2012    1900745.13             0        60.97       3.601
284      2  19-10-2012    1847990.41             0        68.08       3.594
285      2  26-10-2012    1834458.35             0        69.79       3.506

            cpi  unemployment
143  210.752605         8.324
144  210.897994         8.324
145  210.945160         8.324
146  210.975957         8.324
147  211.006754         8.324
..          ...           ...
281  222.616433         6.565
282  222.815930         6.170
283  223.015426         6.170
284  223.059808         6.170
285  223.078337         6.170

[143 rows x 8 columns]

 NEXT


Store:  3

      store        date  weekly_sales  holiday_flag  temperature  fuel_price  \
286      3  05-02-2010     461622.22             0        45.71       2.572
287      3  12-02-2010     420728.96             1        47.93       2.548
288      3  19-02-2010     421642.19             0        47.07       2.514
289      3  26-02-2010     407204.86             0        52.05       2.561
290      3  05-03-2010     415202.04             0        53.04       2.625
..     ...         ...           ...           ...          ...         ...
424      3  28-09-2012     389813.02             0        77.46       3.666
425      3  05-10-2012     443557.65             0        72.74       3.617
426      3  12-10-2012     410804.39             0        70.31       3.601
427      3  19-10-2012     424513.08             0        73.44       3.594
428      3  26-10-2012     405432.70             0        74.66       3.506

            cpi  unemployment
286  214.424881         7.368
287  214.574792         7.368
288  214.619887         7.368
289  214.647513         7.368
290  214.675139         7.368
..          ...           ...
424  226.518093         6.334
425  226.721036         6.034
426  226.923979         6.034
427  226.968844         6.034
428  226.987364         6.034

[143 rows x 8 columns]

 NEXT


Store:  4

      store        date  weekly_sales  holiday_flag  temperature  fuel_price  \
429      4  05-02-2010    2135143.87             0        43.76       2.598
430      4  12-02-2010    2188307.39             1        28.84       2.573
431      4  19-02-2010    2049860.26             0        36.45       2.540
432      4  26-02-2010    1925728.84             0        41.36       2.590
433      4  05-03-2010    1971057.44             0        43.49       2.654
..     ...         ...           ...           ...          ...         ...
567      4  28-09-2012    2027620.23             0        71.74       3.666
568      4  05-10-2012    2209835.43             0        63.07       3.620
569      4  12-10-2012    2133026.07             0        57.11       3.603
570      4  19-10-2012    2097266.85             0        64.46       3.610
571      4  26-10-2012    2149594.46             0        63.64       3.514

            cpi  unemployment
429  126.442065         8.623
430  126.496258         8.623
431  126.526286         8.623
432  126.552286         8.623
433  126.578286         8.623
..          ...           ...
567  131.043000         4.077
568  131.075667         3.879
569  131.108333         3.879
570  131.149968         3.879
571  131.193097         3.879

[143 rows x 8 columns]

 NEXT


Store:  5

      store        date  weekly_sales  holiday_flag  temperature  fuel_price  \
572      5  05-02-2010     317173.10             0        39.70       2.572
573      5  12-02-2010     311825.70             1        39.81       2.548
574      5  19-02-2010     303447.57             0        41.14       2.514
575      5  26-02-2010     270281.63             0        46.70       2.561
576      5  05-03-2010     288855.71             0        48.89       2.625
..     ...         ...           ...           ...          ...         ...
710      5  28-09-2012     310141.68             0        78.33       3.666
711      5  05-10-2012     343048.29             0        71.17       3.617
712      5  12-10-2012     325345.41             0        66.24       3.601
713      5  19-10-2012     313358.15             0        69.17       3.594
714      5  26-10-2012     319550.77             0        71.70       3.506

            cpi  unemployment
572  211.653972         6.566
573  211.800470         6.566
574  211.847128         6.566
575  211.877147         6.566
576  211.907165         6.566
..          ...           ...
710  223.574102         5.603
711  223.774444         5.422
712  223.974787         5.422
713  224.019287         5.422
714  224.037814         5.422

[143 rows x 8 columns]

 NEXT


Store:  6

      store        date  weekly_sales  holiday_flag  temperature  fuel_price  \
715      6  05-02-2010    1652635.10             0        40.43       2.572
716      6  12-02-2010    1606283.86             1        40.57       2.548
717      6  19-02-2010    1567138.07             0        43.58       2.514
718      6  26-02-2010    1432953.21             0        47.10       2.561
719      6  05-03-2010    1601348.82             0        49.63       2.625
..     ...         ...           ...           ...          ...         ...
853      6  28-09-2012    1369131.46             0        77.82       3.666
854      6  05-10-2012    1518177.71             0        70.84       3.617
855      6  12-10-2012    1459396.84             0        65.43       3.601
856      6  19-10-2012    1436883.99             0        69.68       3.594
857      6  26-10-2012    1431426.34             0        72.34       3.506

            cpi  unemployment
715  212.622352         7.259
716  212.770042         7.259
717  212.816155         7.259
718  212.845337         7.259
719  212.874519         7.259
..          ...           ...
853  224.602971         5.668
854  224.804222         5.329
855  225.005473         5.329
856  225.050101         5.329
857  225.068625         5.329

[143 rows x 8 columns]

 NEXT


Store:  7

       store        date  weekly_sales  holiday_flag  temperature  fuel_price  \
858       7  05-02-2010     496725.44             0        10.53       2.580
859       7  12-02-2010     524104.92             1        25.90       2.572
860       7  19-02-2010     506760.54             0        27.28       2.550
861       7  26-02-2010     496083.24             0        24.91       2.586
862       7  05-03-2010     491419.55             0        35.86       2.620
...     ...         ...           ...           ...          ...         ...
996       7  28-09-2012     525545.76             0        50.64       3.789
997       7  05-10-2012     505830.56             0        48.43       3.779
998       7  12-10-2012     503463.93             0        41.43       3.760
999       7  19-10-2012     516424.83             0        43.01       3.750
1000      7  26-10-2012     495543.28             0        42.53       3.686

             cpi  unemployment
858   189.381697         9.014
859   189.464272         9.014
860   189.534100         9.014
861   189.601802         9.014
862   189.669505         9.014
...          ...           ...
996   198.590328         7.872
997   198.822132         7.557
998   199.053937         7.557
999   199.148196         7.557
1000  199.219532         7.557

[143 rows x 8 columns]

 NEXT


Store:  8

       store        date  weekly_sales  holiday_flag  temperature  fuel_price  \
1001      8  05-02-2010    1004137.09             0        34.14       2.572
1002      8  12-02-2010     994801.40             1        33.34       2.548
1003      8  19-02-2010     963960.37             0        39.10       2.514
1004      8  26-02-2010     847592.11             0        37.91       2.561
1005      8  05-03-2010     881503.95             0        45.64       2.625
...     ...         ...           ...           ...          ...         ...
1139      8  28-09-2012     884724.41             0        71.10       3.666
1140      8  05-10-2012     976436.02             0        61.41       3.617
1141      8  12-10-2012     927511.99             0        55.03       3.601
1142      8  19-10-2012     900309.75             0        62.99       3.594
1143      8  26-10-2012     891671.44             0        64.74       3.506

             cpi  unemployment
1001  214.471451         6.299
1002  214.621419         6.299
1003  214.666488         6.299
1004  214.694074         6.299
1005  214.721659         6.299
...          ...           ...
1139  226.567571         5.401
1140  226.770558         5.124
1141  226.973545         5.124
1142  227.018417         5.124
1143  227.036936         5.124

[143 rows x 8 columns]

 NEXT


Store:  9

       store        date  weekly_sales  holiday_flag  temperature  fuel_price  \
1144      9  05-02-2010     549505.55             0        38.01       2.572
1145      9  12-02-2010     552677.48             1        37.08       2.548
1146      9  19-02-2010     511327.90             0        43.06       2.514
1147      9  26-02-2010     473773.27             0        43.83       2.561
1148      9  05-03-2010     507297.88             0        48.43       2.625
...     ...         ...           ...           ...          ...         ...
1282      9  28-09-2012     516361.06             0        76.80       3.666
1283      9  05-10-2012     606755.30             0        66.61       3.617
1284      9  12-10-2012     558464.80             0        60.09       3.601
1285      9  19-10-2012     542009.46             0        68.01       3.594
1286      9  26-10-2012     549731.49             0        69.52       3.506

             cpi  unemployment
1144  214.655459         6.415
1145  214.805653         6.415
1146  214.850618         6.415
1147  214.878045         6.415
1148  214.905472         6.415
...          ...           ...
1282  226.763073         5.277
1283  226.966232         4.954
1284  227.169392         4.954
1285  227.214288         4.954
1286  227.232807         4.954

[143 rows x 8 columns]

 NEXT


Store:  10

       store        date  weekly_sales  holiday_flag  temperature  fuel_price  \
1287     10  05-02-2010    2193048.75             0        54.34       2.962
1288     10  12-02-2010    2176028.52             1        49.96       2.828
1289     10  19-02-2010    2113432.58             0        58.22       2.915
1290     10  26-02-2010    2006774.96             0        52.77       2.825
1291     10  05-03-2010    1987090.09             0        55.92       2.877
...     ...         ...           ...           ...          ...         ...
1425     10  28-09-2012    1694862.41             0        82.52       3.966
1426     10  05-10-2012    1758971.38             0        80.88       4.132
1427     10  12-10-2012    1713889.11             0        76.03       4.468
1428     10  19-10-2012    1734834.82             0        72.71       4.449
1429     10  26-10-2012    1744349.05             0        70.50       4.301

             cpi  unemployment
1287  126.442065         9.765
1288  126.496258         9.765
1289  126.526286         9.765
1290  126.552286         9.765
1291  126.578286         9.765
...          ...           ...
1425  131.043000         7.170
1426  131.075667         6.943
1427  131.108333         6.943
1428  131.149968         6.943
1429  131.193097         6.943

[143 rows x 8 columns]

 NEXT


Store:  11

       store        date  weekly_sales  holiday_flag  temperature  fuel_price  \
1430     11  05-02-2010    1528008.64             0        46.04       2.572
1431     11  12-02-2010    1574684.08             1        48.01       2.548
1432     11  19-02-2010    1503298.70             0        48.30       2.514
1433     11  26-02-2010    1336404.65             0        52.79       2.561
1434     11  05-03-2010    1426622.65             0        53.96       2.625
...     ...         ...           ...           ...          ...         ...
1568     11  28-09-2012    1227430.73             0        77.67       3.666
1569     11  05-10-2012    1422794.26             0        73.37       3.617
1570     11  12-10-2012    1311965.09             0        69.94       3.601
1571     11  19-10-2012    1232073.18             0        73.77       3.594
1572     11  26-10-2012    1200729.45             0        74.26       3.506

             cpi  unemployment
1430  214.424881         7.368
1431  214.574792         7.368
1432  214.619887         7.368
1433  214.647513         7.368
1434  214.675139         7.368
...          ...           ...
1568  226.518093         6.334
1569  226.721036         6.034
1570  226.923979         6.034
1571  226.968844         6.034
1572  226.987364         6.034

[143 rows x 8 columns]

 NEXT


Store:  12

       store        date  weekly_sales  holiday_flag  temperature  fuel_price  \
1573     12  05-02-2010    1100046.37             0        49.47       2.962
1574     12  12-02-2010    1117863.33             1        47.87       2.946
1575     12  19-02-2010    1095421.65             0        54.83       2.915
1576     12  26-02-2010    1048617.17             0        50.23       2.825
1577     12  05-03-2010    1077018.27             0        53.77       2.987
...     ...         ...           ...           ...          ...         ...
1711     12  28-09-2012     880415.67             0        81.22       3.966
1712     12  05-10-2012     979825.92             0        81.61       3.966
1713     12  12-10-2012     934917.47             0        71.74       4.468
1714     12  19-10-2012     960945.43             0        68.66       4.449
1715     12  26-10-2012     974697.60             0        65.95       4.301

             cpi  unemployment
1573  126.442065        13.975
1574  126.496258        13.975
1575  126.526286        13.975
1576  126.552286        13.975
1577  126.578286        13.975
...          ...           ...
1711  131.043000        10.926
1712  131.075667        10.199
1713  131.108333        10.199
1714  131.149968        10.199
1715  131.193097        10.199

[143 rows x 8 columns]

 NEXT


Store:  13

       store        date  weekly_sales  holiday_flag  temperature  fuel_price  \
1716     13  05-02-2010    1967220.53             0        31.53       2.666
1717     13  12-02-2010    2030933.46             1        33.16       2.671
1718     13  19-02-2010    1970274.64             0        35.70       2.654
1719     13  26-02-2010    1817850.32             0        29.98       2.667
1720     13  05-03-2010    1939980.43             0        40.65       2.681
...     ...         ...           ...           ...          ...         ...
1854     13  28-09-2012    1927664.11             0        64.80       3.821
1855     13  05-10-2012    2041918.74             0        61.79       3.815
1856     13  12-10-2012    1999079.44             0        55.10       3.797
1857     13  19-10-2012    2018010.15             0        52.06       3.781
1858     13  26-10-2012    2035189.66             0        46.97       3.755

             cpi  unemployment
1716  126.442065         8.316
1717  126.496258         8.316
1718  126.526286         8.316
1719  126.552286         8.316
1720  126.578286         8.316
...          ...           ...
1854  131.043000         5.765
1855  131.075667         5.621
1856  131.108333         5.621
1857  131.149968         5.621
1858  131.193097         5.621

[143 rows x 8 columns]

 NEXT


Store:  14

       store        date  weekly_sales  holiday_flag  temperature  fuel_price  \
1859     14  05-02-2010    2623469.95             0        27.31       2.784
1860     14  12-02-2010    1704218.84             1        27.73       2.773
1861     14  19-02-2010    2204556.70             0        31.27       2.745
1862     14  26-02-2010    2095591.63             0        34.89       2.754
1863     14  05-03-2010    2237544.75             0        37.13       2.777
...     ...         ...           ...           ...          ...         ...
1997     14  28-09-2012    1522512.20             0        64.88       3.997
1998     14  05-10-2012    1687592.16             0        64.89       3.985
1999     14  12-10-2012    1639585.61             0        54.47       4.000
2000     14  19-10-2012    1590274.72             0        56.47       3.969
2001     14  26-10-2012    1704357.62             0        58.85       3.882

             cpi  unemployment
1859  181.871190         8.992
1860  181.982317         8.992
1861  182.034782         8.992
1862  182.077469         8.992
1863  182.120157         8.992
...          ...           ...
1997  192.013558         8.684
1998  192.170412         8.667
1999  192.327265         8.667
2000  192.330854         8.667
2001  192.308899         8.667

[143 rows x 8 columns]

 NEXT


Store:  15

       store        date  weekly_sales  holiday_flag  temperature  fuel_price  \
2002     15  05-02-2010     652122.44             0        19.83       2.954
2003     15  12-02-2010     682447.10             1        22.00       2.940
2004     15  19-02-2010     660838.75             0        27.54       2.909
2005     15  26-02-2010     564883.20             0        29.87       2.910
2006     15  05-03-2010     605325.43             0        31.79       2.919
...     ...         ...           ...           ...          ...         ...
2140     15  28-09-2012     553901.97             0        57.13       4.158
2141     15  05-10-2012     573498.64             0        59.57       4.151
2142     15  12-10-2012     551799.63             0        49.12       4.186
2143     15  19-10-2012     555652.77             0        52.89       4.153
2144     15  26-10-2012     558473.60             0        55.75       4.071

             cpi  unemployment
2002  131.527903         8.350
2003  131.586613         8.350
2004  131.637000         8.350
2005  131.686000         8.350
2006  131.735000         8.350
...          ...           ...
2140  138.739500         8.193
2141  138.825600         7.992
2142  138.911700         7.992
2143  138.833613         7.992

In [64]:
df_gb_store["weekly_sales"].agg(["sum","mean"])

                sum          mean
store
1      2.224028e+08  1.555264e+06
2      2.753824e+08  1.925751e+06
3      5.758674e+07  4.027044e+05
4      2.995440e+08  2.094713e+06
5      4.547569e+07  3.180118e+05
6      2.237561e+08  1.564728e+06
7      8.159828e+07  5.706173e+05
8      1.299512e+08  9.087495e+05
9      7.778922e+07  5.439806e+05
10     2.716177e+08  1.899425e+06
11     1.939628e+08  1.356383e+06
12     1.442872e+08  1.009002e+06
13     2.865177e+08  2.003620e+06
14     2.889999e+08  2.020978e+06
15     8.913368e+07  6.233125e+05
16     7.425243e+07  5.192477e+05
17     1.277821e+08  8.935814e+05
18     1.551147e+08  1.084718e+06
19     2.066349e+08  1.444999e+06
20     3.013978e+08  2.107677e+06
21     1.081179e+08  7.560691e+05
22     1.470756e+08  1.028501e+06
23     1.987506e+08  1.389864e+06
24     1.940160e+08  1.356755e+06
25     1.010612e+08  7.067215e+05
26     1.434164e+08  1.002912e+06
27     2.538559e+08  1.775216e+06
28     1.892637e+08  1.323522e+06
29     7.714155e+07  5.394514e+05
30     6.271689e+07  4.385796e+05
31     1.996139e+08  1.395901e+06
32     1.668192e+08  1.166568e+06
33     3.716022e+07  2.598617e+05
34     1.382498e+08  9.667816e+05
35     1.315207e+08  9.197250e+05
36     5.341221e+07  3.735120e+05
37     7.420274e+07  5.189003e+05
38     5.515963e+07  3.857317e+05
39     2.074455e+08  1.450668e+06
40     1.378703e+08  9.641280e+05
41     1.813419e+08  1.268125e+06
42     7.956575e+07  5.564039e+05
43     9.056544e+07  6.333247e+05
44     4.329309e+07  3.027489e+05
45     1.123953e+08  7.859814e+05